BookExperience.Web/Controllers/BookController.cs
namespace BookExperience.Web.Controllers
{
    using AutoMapper;
    using BookExperience.Core.Extensions;
    using BookExperience.Core.Models.Books;
    using BookExperience.Core.Services.Author;
    using BookExperience.Core.Services.Book;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using static BookExperience.Infrastrucutre.Data.DataConstants;

    public class BookController : BaseController
    {
        private readonly IBookService bookService;
        private readonly IMapper mapper;
        private readonly IAuthorService authorService;
        public BookController(IBookService bookService, IMapper mapper, IAuthorService authorService)
        {
            this.bookService = bookService;
            this.mapper = mapper;
            this.authorService = authorService;
        }

        [HttpGet]
        public IActionResult Add()
        {
            return View(new BookFormModel
            {
                Genres = this.bookService.AllGenres()
            });
        }

        [HttpPost]
        public async Task<IActionResult> Add(BookFormModel book, List<IFormFile> BookPhoto)
        {
            if (BookPhoto == null || BookPhoto.Count == 0)
            {
                book.Genres = this.bookService.AllGenres();

                return View(book);
            }

            if (this.ModelState.IsValid == false)
            {
                book.Genres = this.bookService.AllGenres();

                return View(book);
            }

            await this.bookService.Create(book.Title, book.AuthorFirstName, book.AuthorLastName, book.PublisherName, BookPhoto, book.Language, book.GenresId, book.Pages, book.IsRecommended, User.GetId(), book.Description);

            TempData[GlobalMessageKey] = "Thank you for adding this book!";

            return RedirectToAction(nameof(Mine));
        }

        [HttpGet]
        [AllowAnonymous]
        public IActionResult All([FromQuery] AllBooksQueryModel query)
        {
            BookQueryModel queryResult = this.bookService.All(
                 query.Title,
                 query.SearchTerm,
                 query.Sorting,
                 query.CurrentPage,
                 AllBooksQueryModel.BooksPerPage);

            IEnumerable<string>? bookTitles = this.bookService
                .AllTitles()
                .ToList();

            query.Titles = bookTitles;
            query.TotalBooks = queryResult.TotalBooks;
            query.Books = queryResult.Books;

            return View(query);
        }

        [HttpGet]
        [HttpGet]
        [AllowAnonymous]
        public IActionResult Details(int id)
        {
            BookDetailsModel book = this.bookService.GetDetailsForBookById(id);

            if (this.ModelState.IsValid == false)
            {
                return RedirectToAction("Error", "Home");
            }

            BookDetailsModel bookForm = this.mapper.Map<BookDetailsModel>(book);

            return View(bookForm);
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            BookDetailsModel? book = this.bookService.GetDetailsForBookById(id);
            string userId = User.GetId();
            if (book.UserId != userId)
            {
                return RedirectToAction("Error", "Home");
            }
            if (book == null)
            {
                return RedirectToAction("Error", "Home");
            }

            BookFormModel bookForm = this.mapper.Map<BookFormModel>(book);
            bookForm.Genres = this.bookService.AllGenres();

            return View(bookForm);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, BookFormModel book, List<IFormFile> BookPhoto)
        {
            if (BookPhoto == null || BookPhoto.Count == 0)
            {
                book.Genres = this.bookService.AllGenres();

                return View(book);
            }

            if (this.ModelState.IsValid == false)
            {
                book.Genres = this.bookService.AllGenres();

                return View(book);
            }

            await this.bookService.Edit(
                id,
                book.Title,
                BookPhoto,
                book.Language,
                book.GenresId,
                book.Pages,
                book.IsRecommended,
                book.AuthorFirstName,
                book.AuthorLastName,
                book.PublisherName,
                book.Description);


            TempData[GlobalMessageKey] = "You edit this book successfully!";

            return RedirectToAction(nameof(Mine));
        }

        [HttpGet]
        public IActionResult Mine()
        {
            IEnumerable<MineBooksModel> myBooks = this.bookService
                .ByUser(this.User.GetId())
                .ToList();

            return View(myBooks);
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            BookDetailsModel? book = this.bookService.GetDetailsForBookById(id);
            string userId = User.GetId();
            if (book.UserId != userId)
            {
                return RedirectToAction("Error", "Home");
            }
            if (book == null)
            {
                return RedirectToAction("Error", "Home");
            }

            bool findBook = this.bookService.Delete(id);

            if (findBook == true)
            {
                TempData[GlobalMessageKey] = "You delete this book successfully!";
            }

            return RedirectToAction(nameof(Mine));
        }

        public IActionResult GetAuthorBooks(int id)
        {
            IEnumerable<MineBooksModel> books = this.bookService
                .GetBooksByAuthorId(id)
                .ToList();

            return View(books);
        }

    }
}

BookExperience.Web/Controllers/GenreController.cs
namespace BookExperience.Web.Controllers
{
    using BookExperience.Core.Models.Genres;
    using BookExperience.Core.Services.Genre;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;

    public class GenreController : Controller
    {
        private readonly IGenreService genreService;
        public GenreController(IGenreService genreService)
        {
            this.genreService = genreService;
        }

        [AllowAnonymous]
        public IActionResult FilteredByGenres(int id)
        {
            GenresFilterModel model = new GenresFilterModel();

            if (id < 0)
            {
                return RedirectToAction("Error", "Home");
            }

            model = this.genreService.GetBooksSortedByGenre(id);

            if (model == null)
            {
                return RedirectToAction("Error", "Home");
            }

            return View(model);
        }
    }
}

BookExperience.Web/Controllers/WantedBooksController.cs
namespace BookExperience.Web.Controllers
{
    using BookExperience.Core.Extensions;
    using BookExperience.Core.Services.Book;
    using BookExperience.Core.Services.WantedBooks;
    using BookExperience.Infrastrucutre.Data.Models;
    using Microsoft.AspNetCore.Mvc;
    using static BookExperience.Infrastrucutre.Data.DataConstants;

    public class WantedBooksController : BaseController
    {
        private IBookService bookService;
        private IWantedBooksService wantedBooks;

        public WantedBooksController(IBookService bookService, IWantedBooksService wantedBooks)
        {
            this.bookService = bookService;
            this.wantedBooks = wantedBooks;
        }

        [HttpGet]
        public IActionResult AddAsWanted(int id)
        {
            Book? book = this.bookService.FindBook(id);

            if (book is null)
            {
                return RedirectToAction("Error", "Home");
            }
            this.wantedBooks.AddWantedBooks(book.Id, User.GetId());
            TempData[GlobalMessageKey] = "You marked the book as wanted!";

            return RedirectToAction("All", "Book");
        }

        [HttpGet]
        public IActionResult RemoveFromWanted(int id)
        {
            if (id == 0)
            {
                return RedirectToAction("Error", "Home");
            }

            this.wantedBooks.RemoveWantedBook(id);
            TempData[GlobalMessageKey] = "You remove the book from wanted!";

            return RedirectToAction("All", "Book");
        }

        [HttpGet]
        public IActionResult WantedBooks()
        => View();
    }
}

BookExperience.Web/Views/Shared/_Layout.cshtml
@using BookExperience.Core.Services.Author
@inject SignInManager<ApplicationUser> SignInManager
@using static BookExperience.Infrastrucutre.Data.DataConstants;
@inject IAuthorService authorService;


<!DOCTYPE html>
<!--
This is a starter template page. Use this page to start your new project from
scratch. This page gets rid of all links and provides the needed markup only.
-->
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">

	<!-- Google Font: Source Sans Pro -->
	<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
	<!-- Font Awesome Icons -->
	<link rel="stylesheet" href="~/plugins/fontawesome-free/css/all.min.css"/>
	<!-- Theme style -->
	<link rel="stylesheet" href="~/css/dropdown.css"/>
	<link rel="stylesheet" href="~/css/adminlte.min.css"/>

	<!-- Title-->
	<title>@ViewData["Title"] - Booking Experience </title/>
	<!-- Toastr-->
	<link rel="stylesheet" href="~/js/toastr/toastr.min.css" />
	<!-- Favicon-->
	 <link rel="icon" type="image/x-icon" href="~/img/Book.png">
	 
	@await RenderSectionAsync("Head",false)
</head>
<body class="hold-transition sidebar-mini">
	<div class="wrapper">

		<!-- Navbar -->
		<nav class="main-header navbar navbar-expand navbar-white navbar-light">
			<!-- Left navbar links -->
				<ul class="navbar-nav">
					<li class="nav-item">
					<a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
				</li>
				<li class="nav-item">
					<a href="/" class="nav-link">Home</a>					
				</li>				
				<li>
						 <a class="nav-link" asp-area="" asp-controller="Book" asp-action="All">All Books<i class="nav-link"></i></a>
				</li>
				</ul>
			<div class="dropdown">
				  <div class="dropdown">
				  <button class="dropbtn">Books Genres</button>
				  <div class="dropdown-content">
					  	 <a asp-controller="Genre" asp-action="FilteredByGenres" asp-route-id="@AdventureStoriesId" class="btn btn-light">Adventure Stories</a>
					  	 <a asp-controller="Genre" asp-action="FilteredByGenres" asp-route-id="@ClassicsId" class="btn btn-light">Classics</a>
					  	 <a asp-controller="Genre" asp-action="FilteredByGenres" asp-route-id="@CrimeId" class="btn btn-light">Crime</a>
					  	 <a asp-controller="Genre" asp-action="FilteredByGenres" asp-route-id="@FantasyId" class="btn btn-light">Fantasy</a>
					  	 <a asp-controller="Genre" asp-action="FilteredByGenres" asp-route-id="@FairyTalesId" class="btn btn-light">Fairy Tales</a>
					  	 <a asp-controller="Genre" asp-action="FilteredByGenres" asp-route-id="@HistoricalFictionId" class="btn btn-light">Historical Fiction</a>
					  	 <a asp-controller="Genre" asp-action="FilteredByGenres" asp-route-id="@HorrorId" class="btn btn-light">Horror</a>
					  	 <a asp-controller="Genre" asp-action="FilteredByGenres" asp-route-id="@HumourAndSatireId" class="btn btn-light">Humour And Satire</a>
					  	 <a asp-controller="Genre" asp-action="FilteredByGenres" asp-route-id="@PhilosophyId" class="btn btn-light">Philosophy</a>
				  </div>
				</div>
				</div>
				<div class="dropdown">
				  <div class="dropdown">
				  <button class="dropbtn">Authors</button>
				  <div class="dropdown-content">
						@{
							var authors = this.authorService.GetAllAuthors();
							foreach (var author in authors)
							{
						  	 <a asp-controller="Book" asp-action="GetAuthorBooks" asp-route-id="@author.Id" class="btn btn-light">@author.FirstName @author.LastName</a>
							}
					 }

				  </div>
				</div>
				</div>
			@if (SignInManager.IsSignedIn(User))
			{
				<div class="dropdown">
				  <button class="dropbtn">Books</button>
				  <div class="dropdown-content">
						 <a class="nav-link" asp-area="" asp-controller="Book" asp-action="Add">Add Book<i class="nav-link"></i></a>
						 <a class="nav-link" asp-area="" asp-controller="Book" asp-action="All">All Books<i class="nav-link"></i></a>
						 <a class="nav-link" asp-area="" asp-controller="Book" asp-action="Mine">My Books<i class="nav-link"></i></a>
						 <a class="nav-link" asp-area="" asp-controller="WantedBooks" asp-action="WantedBooks">Wanted Books<i class="nav-link"></i></a>
				  </div>
				</div>
			}
		
			<!-- Right navbar links -->
			<ul class="navbar-nav ml-auto">
				<!-- Notifications Dropdown Menu -->
				<li class="nav-item">
					<a class="nav-link" data-widget="fullscreen" href="#" role="button">
						<i class="fas fa-expand-arrows-alt"></i>
					</a>
				</li>
			</ul>
			                    <partial name="_LoginPartial" />
		</nav>
		<!-- /.navbar -->
		<!-- Main Sidebar Container -->
		<aside class="main-sidebar sidebar-dark-primary elevation-4">
			<!-- Brand Logo -->
			<a href="/" class="brand-link">
				<img src="~/img/Book.png" alt="Warehouse Logo" class="brand-image img-circle elevation-3" style="opacity: .8">
				<span class="brand-text font-weight-light">Booking Expirience</span>
			</a>
			<!-- Sidebar -->
			<div class="sidebar">
				<partial name="_MainMenu"/> 
				<!-- /.sidebar-menu -->
			</div>
			<!-- /.sidebar -->
		</aside>

		<!-- Content Wrapper. Contains page content -->
		<div class="content-wrapper">
			<!-- Content Header (Page header) -->
			<div class="content-header">
				<div class="container-fluid">
					<div class="row mb-2">
						<div class="col-sm-6">
							</div><!-- /.col -->
						<div class="col-sm-6">
							<ol class="breadcrumb float-sm-right">
								<li class="breadcrumb-item"><a href="#">Home</a></li>
								<li class="breadcrumb-item active">Starter Page</li>
							</ol>
						</div><!-- /.col -->
					</div><!-- /.row -->
				</div><!-- /.container-fluid -->
			</div>
			<!-- /.content-header -->
			<!-- Main content -->
			@if (TempData.ContainsKey(GlobalMessageKey))
				{
					 <div class="alert alert-success text-center" role="alert">
					 @TempData[GlobalMessageKey]
            </div>
				 }
			<div class="content ml-6">
				<div class="container-fluid">
					@RenderBody()

				</div>
				<!-- /.row -->
			</div><!-- /.container-fluid -->
		</div>
		<!-- /.content -->
	</div>
	<!-- /.content-wrapper -->
	<!-- Control Sidebar -->
	<aside class="control-sidebar control-sidebar-dark">
		<!-- Control sidebar content goes here -->
		<div class="p-3">
			<h5>Title</h5>
			<p>Sidebar content</p>
		</div>
	</aside>
	<!-- /.control-sidebar -->
	<!-- Main Footer -->
	<footer class="main-footer">
		<!-- To the right -->
		<div class="float-right d-none d-sm-inline">
			Anything you want
		</div>
		<!-- Default to the left -->
		<strong>Copyright &copy; 2014-@DateTime.Now.Year <a href="/">Booking Expirience 2022 </a>.</strong> All rights reserved.
	</footer>

	<!-- ./wrapper -->
	<!-- jQuery -->
	<script src="~/plugins/jquery/jquery.min.js"></script>
	<!-- Bootstrap 4 -->
	<script src="~/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
	<!-- AdminLTE App -->
	<script src="~/js/adminlte.min.js"></script>
	<script src="~/plugins/toastr/toastr.min.js"></script>

	@await RenderSectionAsync("Scripts",false)
</body>
</html>

BookExperience.Web/Views/Shared/_MainMenu.cshtml
@inject SignInManager<ApplicationUser> SignInManager

<nav class="mt-2">
	<ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
		<!-- Add icons to the links using the .nav-icon class
			 with font-awesome or any other icon font library -->
		<li class="nav-item">
			<a class="nav-link active" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
		</li>
		<li class="nav-item">
			<a class="nav-link active" asp-controller="Book" asp-action="Add">Add Book<i class="nav-link"></i></a>
		</li>
		<li class="nav-item">
			<a class="nav-link active" asp-controller="Book" asp-action="All">All Books<i class="nav-link"></i></a>
		</li>
	</ul>
</nav>